package com.example.st129_gravityfalls_maker.model

data class CustomizeModel(
    val name: String,
    var avatar: String,
    var bg: ArrayList<LayerModel> = arrayListOf(),
    var effect: ArrayList<LayerModel> = arrayListOf(),
    var wing: ArrayList<LayerModel> = arrayListOf(),
    var endhairleft: ArrayList<LayerModel> = arrayListOf(),
    var endhairright: ArrayList<LayerModel> = arrayListOf(),
    var endhair: ArrayList<LayerModel> = arrayListOf(),
    var backhair: ArrayList<LayerModel> = arrayListOf(),
    var earleft1: ArrayList<LayerModel> = arrayListOf(),
    var earleft2: ArrayList<LayerModel> = arrayListOf(),
    var ear: ArrayList<LayerModel> = arrayListOf(),
    var body: ArrayList<LayerModel> = arrayListOf(),
    var head: ArrayList<LayerModel> = arrayListOf(),
    var necklace: ArrayList<LayerModel> = arrayListOf(),
    var beard: ArrayList<LayerModel> = arrayListOf(),
    var eyebrow: ArrayList<LayerModel> = arrayListOf(),
    var chin: ArrayList<LayerModel> = arrayListOf(),
    var leg: ArrayList<LayerModel> = arrayListOf(),
    var shoes: ArrayList<LayerModel> = arrayListOf(),
    var shoulderright: ArrayList<LayerModel> = arrayListOf(),
    var shoulderleft: ArrayList<LayerModel> = arrayListOf(),
    var handright: ArrayList<LayerModel> = arrayListOf(),
    var handleft: ArrayList<LayerModel> = arrayListOf(),
    var bodypaint: ArrayList<LayerModel> = arrayListOf(),
    var facepaint: ArrayList<LayerModel> = arrayListOf(),
    var eye: ArrayList<LayerModel> = arrayListOf(),
    var eyeleft: ArrayList<LayerModel> = arrayListOf(),
    var eyeright: ArrayList<LayerModel> = arrayListOf(),
    var eyelash: ArrayList<LayerModel> = arrayListOf(),
    var irisleft: ArrayList<LayerModel> = arrayListOf(),
    var irisright: ArrayList<LayerModel> = arrayListOf(),
    var mouth: ArrayList<LayerModel> = arrayListOf(),
    var nose: ArrayList<LayerModel> = arrayListOf(),
    var mask: ArrayList<LayerModel> = arrayListOf(),
    var glass: ArrayList<LayerModel> = arrayListOf(),
    var earright1: ArrayList<LayerModel> = arrayListOf(),
    var earright2: ArrayList<LayerModel> = arrayListOf(),
    var sidehair: ArrayList<LayerModel> = arrayListOf(),
    var fronthair: ArrayList<LayerModel> = arrayListOf(),
    var sleeve: ArrayList<LayerModel> = arrayListOf(),
    var trouser: ArrayList<LayerModel> = arrayListOf(),
    var shirt: ArrayList<LayerModel> = arrayListOf(),
    var jacket: ArrayList<LayerModel> = arrayListOf(),
    var lapelpin: ArrayList<LayerModel> = arrayListOf(),
    var pin: ArrayList<LayerModel> = arrayListOf(),
    var collar: ArrayList<LayerModel> = arrayListOf(),
    var hat: ArrayList<LayerModel> = arrayListOf(),
    var horn: ArrayList<LayerModel> = arrayListOf(),
    var accessories: ArrayList<LayerModel> = arrayListOf(),
    var other: ArrayList<LayerModel> = arrayListOf(),
    var hand: ArrayList<LayerModel> = arrayListOf()
)
