package com.example.st129_gravityfalls_maker.model

data class CustomizeModel(
    val name: String,
    var avatar: String,

    var body : ArrayList<LayerModel> = arrayListOf(),
    var head : ArrayList<LayerModel> = arrayListOf(),
    var eye : ArrayList<LayerModel> = arrayListOf(),
    var iris : ArrayList<LayerModel> = arrayListOf(),
    var eyebrow : ArrayList<LayerModel> = arrayListOf(),
    var nose : ArrayList<LayerModel> = arrayListOf(),
    var ear : ArrayList<LayerModel> = arrayListOf(),
    var mouth : ArrayList<LayerModel> = arrayListOf(),
    var beard : ArrayList<LayerModel> = arrayListOf(),
    var facepaint : ArrayList<LayerModel> = arrayListOf(),
    var sidehair : ArrayList<LayerModel> = arrayListOf(),
    var fronthair : ArrayList<LayerModel> = arrayListOf(),
    var backhair : ArrayList<LayerModel> = arrayListOf(),
    var shirt : ArrayList<LayerModel> = arrayListOf(),
    var jacket : ArrayList<LayerModel> = arrayListOf(),
    var glass : ArrayList<LayerModel> = arrayListOf(),
    var hand : ArrayList<LayerModel> = arrayListOf(),
    var necklace : ArrayList<LayerModel> = arrayListOf(),
    var earring : ArrayList<LayerModel> = arrayListOf(),
    var sleeve : ArrayList<LayerModel> = arrayListOf(),
    var accessories : ArrayList<LayerModel> = arrayListOf(),
    var hat : ArrayList<LayerModel> = arrayListOf(),
    var other : ArrayList<LayerModel> = arrayListOf(),
    var wing : ArrayList<LayerModel> = arrayListOf(),
)
